import type { ServicesContent } from "@/types/content";

export const services: ServicesContent = {
  categories: [
    {
      image: "/images/services/mechanical.webp",
      imageAlt: "Mechanic working on a car engine in the workshop",
      items: [
        "Engine repair and maintenance",
        "Transmission (gearbox) service and repair",
        "Brake system repair",
        "Oil and filter changes",
        "Periodic and preventive maintenance",
        "Computer diagnostics and fault scanning",
        "Cooling system and radiator repair",
        "Belt and spare parts replacement",
        "Vehicle preparation for technical inspection",
      ],
      title: "Mechanical services",
    },
    {
      image: "/images/services/electrical.webp",
      imageAlt: "Automotive electrical diagnostics with scan tools",
      items: [
        "Electrical fault inspection and repair",
        "Car computer programming and diagnostics",
        "Wiring harness and electrical cable repair",
        "Sensor diagnostics and repair",
        "Lighting system maintenance and repair",
        "Starting and charging system repair",
        "Battery, alternator, and starter replacement",
        "Modern electronic systems repair",
      ],
      title: "Electrical and electronics",
    },
    {
      image: "/images/services/bodywork.webp",
      imageAlt: "Car bodywork and paint spraying in a professional booth",
      items: [
        "Accident repair for all severity levels",
        "Professional bodywork and structural restoration",
        "Full or partial paint with modern techniques",
        "Original paint color matching",
        "Scratch and dent repair",
        "Bumper repair and renewal",
        "Paint polishing and protection",
        "Restoring the car's original appearance",
      ],
      title: "Bodywork and paint",
    },
    {
      image: "/images/services/ac.webp",
      imageAlt: "Car air conditioning service with gauge equipment",
      items: [
        "AC system inspection and maintenance",
        "AC gas refill",
        "Compressor repair",
        "AC circuit cleaning",
        "Weak cooling diagnosis and repair",
      ],
      title: "Air conditioning",
    },
    {
      image: "/images/services/tires.webp",
      imageAlt: "Tire mounting and wheel service in the garage",
      items: [
        "Tire replacement and repair",
        "Wheel balancing",
        "Wheel alignment",
        "Wheel system inspection",
      ],
      title: "Tires and wheels",
    },
    {
      image: "/images/services/extra.webp",
      imageAlt: "VIP mobile car care service beside a luxury vehicle",
      items: [
        "VIP service",
        "Mobile garage service",
        "Recovery service (vehicle towing and transport)",
        "Car pickup and delivery",
        "Car rental service",
        "Vehicle registration in Dubai and Sharjah",
        "Full inspection before buying a car",
        "Pre-travel inspection",
        "Genuine and high-quality spare parts installation",
        "Accurate technical reports on vehicle condition",
      ],
      title: "Additional services",
    },
  ],
  description:
    "Complete mechanical, electrical, body, AC, tire, and additional care under one roof, delivered with modern equipment and specialized technicians.",
  title: "Our Services",
};
